utf8 = require("utf8")
socket = require("socket") --网络通信
ffi = require("ffi") --调用C语言库
require("function/beat_and_time")
require("function/log")
require("function/string")
require("function/table")
require("function/save")
require("function/RGB")
nativefs = require("function/nativefs")
dkjson = require("function/dkjson")
require("function/mc_to_dakumi")
easings = require('function/easings')
require("function/input_box")
require("function/animation")
require("function/button")
require("function/bezier")
require("function/math")
require("function/switch")
ui_style = require("function/ui_style")
require("function/track")
require("function/note")
require("function/event")


require("objact/button_denom")
require("objact/button_music_speed")
require('objact/button_track_scale')
require("objact/button_in_play_fence")
require('objact/button_export')
require('objact/button_save')
require("objact/mouse")
require("objact/button_music_play")
require('objact/message_box')
require("objact/note")
require("objact/note_edit_inplay")
require('objact/demo_in_play')
require("objact/alt_note_event")
require("objact/event")
require("objact/hit")
require('objact/note_edit')
require('objact/event_edit')
require('objact/events_edit')
require('objact/event_edit_bezier')
require('objact/button_track')
require('objact/button_chart_info')
require('objact/button_event_edit_default_bezier')
require('objact/button_delete_chart')
require('objact/button_delete_music')
require('objact/button_open_directory')
require('objact/button_edit_chart')
require('objact/button_new_chart')
require('objact/button_break')
require('objact/button_settings')
require('objact/button_to_github')
require('objact/button_to_dakumi')
require('objact/button_tracks_edit')
--require('objact/button_select_file')
require('objact/chart_info')
require('objact/tracks_edit')
require('objact/button_bpm_list')
require('objact/slider')
require('objact/copy')
require('objact/redo')
require('objact/settings')
require('objact/demo_mode')
require('objact/denom_play')
require('objact/note_play_in_edit')
require('objact/language')
require('objact/ui')
--require('objact/file_selector')
--require('objact/button_selector_break')
--require('objact/button_selector_close')
--require('objact/button_selector_refresh')

require("room/select")
require("room/play")
require("room/sidebar")
require("room/edit_tool")
require("room/tracks_edit")